# Generated by Django 5.1.4 on 2024-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiempo_creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
